<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MacBook-Pro.attlocal.net" failures="10" tests="162" name="testrunners.MyTestRunner" time="244.376" errors="0" timestamp="2023-08-05T06:26:56 PDT" skipped="0">
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.314"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.666"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.715"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.876"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.384"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.867"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.651"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.376"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.255"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.837"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.345"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.867"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.696">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.stepdefinitions.RegisterSteps.it_should_display_an_error_message(RegisterSteps.java:81)
at ✽.It should display an error message "Username already exists"(file:///Users/Roops/git/DS_Algo/src/test/resources/features/CRegister.feature:34)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.391"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.672"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.440"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.179"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.390"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.126">
    <failure message="expected [Successful Submission] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Successful Submission] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.stepdefinitions.ArraySteps.the_user_should_be_presented_with_successful_submission_message_on_question_three(ArraySteps.java:569)
at ✽.The user should be presented with successful submission message on question three(file:///Users/Roops/git/DS_Algo/src/test/resources/features/FArray.feature:207)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.686"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.243"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.683">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.stepdefinitions.RegisterSteps.it_should_display_an_error_message(RegisterSteps.java:81)
at ✽.It should display an error message "Password can’t be commonly used password"(file:///Users/Roops/git/DS_Algo/src/test/resources/features/CRegister.feature:69)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.520"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.869"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.631"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.555"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.363"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.499"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.502"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.518"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.456"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.631"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.592"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.087"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.324"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.907"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.484"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.420"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.583"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.718"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.624"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.264"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.130"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.553"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.564"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="4.472"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.651"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="5.189"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.727"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.315"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.131"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.348"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.059"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.067"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.012">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.stepdefinitions.RegisterSteps.it_should_display_an_error_message(RegisterSteps.java:81)
at ✽.It should display an error message "Please enter a valid username"(file:///Users/Roops/git/DS_Algo/src/test/resources/features/CRegister.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.448"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.667"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.848"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.345"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.209"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.567"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.963"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.740"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.222"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.175"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.473"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.142"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.463"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.129"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.263"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.268"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.767"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.124"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.767"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="4.869"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.475">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.stepdefinitions.RegisterSteps.it_should_display_an_error_message(RegisterSteps.java:81)
at ✽.It should display an error message "Password should contain at least 8 characters"(file:///Users/Roops/git/DS_Algo/src/test/resources/features/CRegister.feature:48)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.432"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.875"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.406"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.581"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.743"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.831"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.932"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.943"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.523"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.264"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="4.375"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.549"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.508"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.709"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.648"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.235"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.112"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.357"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.276"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.759"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.495">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.stepdefinitions.RegisterSteps.it_should_display_an_error_message(RegisterSteps.java:81)
at ✽.It should display an error message "Password can’t be entirely numeric."(file:///Users/Roops/git/DS_Algo/src/test/resources/features/CRegister.feature:55)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.745">
    <failure message="expected [Successful Submission] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Successful Submission] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.stepdefinitions.ArraySteps.the_user_should_be_presented_with_successful_submission_message_on_question_two(ArraySteps.java:489)
at ✽.The user should be presented with successful submission message on question two(file:///Users/Roops/git/DS_Algo/src/test/resources/features/FArray.feature:176)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.600"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.595"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.795"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.489"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.364"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.738"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.916"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.419"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.418"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.094"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.409"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.838"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="4.704"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.880"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.881"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.653"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.998"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.130"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.695"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.027"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.696"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.152"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.679">
    <failure message="expected [Successful Submission] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Successful Submission] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.stepdefinitions.ArraySteps.the_user_should_be_presented_with_successful_submission_message_for_search_the_array(ArraySteps.java:410)
at ✽.The user should be presented with successful submission message for Search the array(file:///Users/Roops/git/DS_Algo/src/test/resources/features/FArray.feature:145)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.363"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.407"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.702"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.600"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.669"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.656"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.114"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.740"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.956"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.267"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.734"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.301"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.048"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.599"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.958"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.407"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.670"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.333"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.216">
    <failure message="expected [Successful Submission] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Successful Submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.stepdefinitions.ArraySteps.the_user_should_be_presented_with_successful_submission_message_on_question_four(ArraySteps.java:647)
at ✽.The user should be presented with successful submission message on question four(file:///Users/Roops/git/DS_Algo/src/test/resources/features/FArray.feature:236)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.670"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.070"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.329"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.414"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.481"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.788"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.383"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.692"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.938"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.774">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.stepdefinitions.RegisterSteps.it_should_display_an_error_message(RegisterSteps.java:81)
at ✽.It should display an error message "password can’t be too similar to your other personal information."(file:///Users/Roops/git/DS_Algo/src/test/resources/features/CRegister.feature:62)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.521"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.132"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.339"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.972"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="3.843"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.133"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.598"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.251"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="1.451"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.368"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="2.179"/>
  <testcase classname="testrunners.MyTestRunner" name="runScenario" time="0.494"/>
</testsuite> <!-- testrunners.MyTestRunner -->
